services:
  # web1:
  #   image: httpd:2.4
  #   ports:
  #     - 8081:80
  # web2:
  #   image: bitnami/apache
  #   ports:
  #     - 8080:8080
  web:
    build: apacheserver
    hostname: apacheserver
    ports:
      - 80:80
    volumes:
      - ./apacheserver/martin.lan:/opt/web/martin.lan
      - ./apacheserver/sites-enabled/martin.lan.conf:/etc/apache2/sites-enabled/martin.lan.conf
      - ./apacheserver/omeusitio.lan:/opt/web/omeusitio.lan
      - ./apacheserver/sites-enabled/omeusitio.lan.conf:/etc/apache2/sites-enabled/omeusitio.lan.conf
      - ./apacheserver/novositio.lan:/opt/web/novositio.lan
      - ./apacheserver/sites-enabled/novositio.lan.conf:/etc/apache2/sites-enabled/novositio.lan.conf
      - ./apacheserver/sites-enabled/novositio.lan.ssl.conf:/etc/apache2/sites-enabled/novositio.lan.ssl.conf
      - ./apacheserver/ssl/novositio.lan.key:/etc/ssl/private/novositio.lan.key
      - ./apacheserver/ssl/novositio.lan.pem:/etc/ssl/certs/novositio.lan.pem
    networks:
      redeapache:
        aliases:
          - martin.lan
          - www.martin.lan
          - eq1.martin.lan
          - omeusitio.lan
          - www.omeusitio.lan
          - novositio.lan
          - www.novositio.lan
    develop:
      watch:
        - path: ./apacheserver/sites-enabled/martin.lan
          action: restart
  
  cliente:
    build: cliente
    hostname: cliente
    networks:
      - redeapache
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  redeapache:
    ipam:
        config:
          - subnet: 192.168.58.128/25